#url: https://scottmcallister.github.io

# Site settings
title: Scott McAllister
email: mr.scott.mcallister@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0099FF
  secondary: 0066FF
  secondary-dark: 333

# User settings
username: Scott McAllister
user_description: Software Developer
user_title: Scott McAllister
email: mr.scott.mcallister@gmail.com
github_username:  scottmcallister
linkedin_link:  https://ca.linkedin.com/in/scott-mcallister-89028ba1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About Me
    url: /about
  - title: Blog
    url: /tags
  - title: Projects
    url: /series



# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/ScottVictorMcAllister
  - title: linkedin
    url: https://ca.linkedin.com/pub/scott-mcallister/a1/28b/890
  - title: github
    url: http://github.com/scottmcallister
